# Generated by Django 4.1.5 on 2023-01-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['author_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, verbose_name='date published')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=200)),
                ('published_authors', models.ManyToManyField(through='books.Book', to='books.author', verbose_name='Published Authors')),
                ('published_books', models.ManyToManyField(to='books.book', verbose_name='Published Books')),
            ],
            options={
                'ordering': ['publisher_name'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.publisher', verbose_name='book publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='book author'),
        ),
    ]
