# Generated by Django 4.1.5 on 2023-01-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author_author_bio_publisher_publisher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_publisher', to='books.publisher', verbose_name='book publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_author', to='books.author', verbose_name='book author'),
        ),
    ]
